import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from hashlib import sha256
from Crypto.Cipher import AES
from Crypto.Util import Padding
import random
import string
import os

def encrypt_file(pswd, iv, file):
    key = sha256(pswd.encode()).digest()
    with open(file, "rb") as f:
        data = f.read()

    cipher = AES.new(key, AES.MODE_CBC, iv)
    paddeddata = Padding.pad(data, 16)
    encrypteddata = cipher.encrypt(paddeddata)

    # Ask the user to select a folder to save the encrypted file and IV
    save_folder = filedialog.askdirectory(title="Select a folder to save the encrypted file")
    if not save_folder:
        messagebox.showerror("Error", "No folder selected. Encryption aborted.")
        return

    # Get the original file name without the directory
    original_file_name = os.path.basename(file)
    
    # Save the encrypted file in the selected folder
    encrypted_file_path = os.path.join(save_folder, original_file_name)
    with open(encrypted_file_path, "wb") as ef:
        ef.write(encrypteddata)

    # Save the IV in the selected folder
    iv_file_path = os.path.join(save_folder, "AES_IV.txt")
    with open(iv_file_path, "w") as ivf:
        ivf.write(f"Encryption of: {original_file_name}\n\n-----BEGIN AES INITIALIZATION VECTOR BLOCK-----\n{iv.decode()}\n-----END AES INITIALIZATION VECTOR BLOCK-----")

    messagebox.showinfo("Success", f"Encryption complete!\nFiles saved in: {save_folder}")

# The rest of the code remains unchanged

def decrypt_file(pswd, iv, file):
    key = sha256(pswd.encode()).digest()
    with open(file, "rb") as f:
        data = f.read()

    cipher = AES.new(key, AES.MODE_CBC, iv)
    decrypteddata = cipher.decrypt(data)
    unpaddeddata = Padding.unpad(decrypteddata, 16)

    with open(file, "wb") as ef:
        ef.write(unpaddeddata)

    messagebox.showinfo("Success", f"Decryption complete!")

def select_file():
    file_path = filedialog.askopenfilename()
    file_entry.delete(0, tk.END)
    file_entry.insert(0, file_path)

def encrypt():
    file = file_entry.get()
    pswd = password_entry.get()
    if not file or not pswd:
        messagebox.showerror("Error", "Please select a file and enter a password.")
        return
    iv = ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in range(16))
    encrypt_file(pswd, iv.encode(), file)

def decrypt():
    file = file_entry.get()
    pswd = password_entry.get()
    iv = iv_entry.get()
    if not file or not pswd or not iv:
        messagebox.showerror("Error", "Please select a file, enter a password, and enter the IV.")
        return
    if len(iv) != 16:
        messagebox.showerror("Error", "IV must be 16 characters long.")
        return
    decrypt_file(pswd, iv.encode(), file)

def show_info():
    info = (
        "Cryptic (version 4.0) is a cryptography project started in 2021 "
        "that encrypts and decrypts your files using AES-256. It works with a strong password "
        "chosen by the user and a 16-byte initialization vector (IV) generated by the program. "
        "Keep the IV secret, as you'll need it to decrypt your files."
    )
    messagebox.showinfo("Information", info)

# GUI setup
root = tk.Tk()
root.title("Cryptic")
root.geometry("650x300")
root.resizable(False, False)

# Style configuration
style = ttk.Style()
style.configure("TLabel", font=("Segoe UI", 11))
style.configure("TButton", font=("Segoe UI", 11), padding=5)
style.configure("TEntry", font=("Segoe UI", 11), padding=5)

# Main frame
frame = ttk.Frame(root, padding=15)
frame.pack(fill="both", expand=True)

# Centering all columns and rows
frame.columnconfigure(0, weight=1)
frame.columnconfigure(1, weight=1)
frame.columnconfigure(2, weight=1)

# Banner
banner_label = ttk.Label(frame, text="Cryptic", font=("Segoe UI", 18, "bold"), foreground="#333")
banner_label.grid(row=0, column=0, columnspan=3, pady=(0, 20), sticky="n")

# File selection
file_label = ttk.Label(frame, text="File:")
file_label.grid(row=1, column=0, sticky="e")
file_entry = ttk.Entry(frame, width=30)
file_entry.grid(row=1, column=1, padx=(0, 10))
file_button = ttk.Button(frame, text="Browse", command=select_file)
file_button.grid(row=1, column=2, sticky="w")

# Password input
password_label = ttk.Label(frame, text="Password:")
password_label.grid(row=2, column=0, sticky="e", pady=(10, 0))
password_entry = ttk.Entry(frame, show="*", width=30)
password_entry.grid(row=2, column=1, columnspan=2, pady=(10, 20), sticky="w")

# IV input
iv_label = ttk.Label(frame, text="IV (for decryption):")
iv_label.grid(row=3, column=0, sticky="e")
iv_entry = ttk.Entry(frame, width=30)
iv_entry.grid(row=3, column=1, columnspan=2, pady=(0, 20), sticky="w")

# Buttons
button_frame = ttk.Frame(frame)
button_frame.grid(row=4, column=0, columnspan=3, pady=10)

encrypt_button = ttk.Button(button_frame, text="Encrypt", command=encrypt)
encrypt_button.grid(row=0, column=0, padx=5)

decrypt_button = ttk.Button(button_frame, text="Decrypt", command=decrypt)
decrypt_button.grid(row=0, column=1, padx=5)

info_button = ttk.Button(button_frame, text="Info", command=show_info)
info_button.grid(row=0, column=2, padx=5)

exit_button = ttk.Button(button_frame, text="Exit", command=root.quit)
exit_button.grid(row=0, column=3, padx=5)

root.mainloop()
